### ISSUE TITLE
How does Juggernaut compare to Faye?

### ISSUE THREAD

**Issue by michaelsbradleyjr** [maccman/juggernaut#2]
I'm going to be looking at Juggernaut for use in my app.

Currently, I'm using Faye and it's great, though I feel the internals are hard to understand and adjust, if one needs to do that. I think that's partly owing to the complexity of the Bayeux protocol (which is related to Comet, of course) of which Faye is an implementation (including a websockets implementation not described in the protocol spec). It's also owing, I think, to jcoglan's having in mind that it's Faye's external API that should be "dirt simple" and his not coding it in a manner that's geared for hackability, per se.  And I think it's owing to the fact that jcoglan is a wizard and he wrote the code using just about every trick he knows to make the JS as lean and fast as possible.

Anyway, would you be willing to offer a comparison of your juggernaut with Faye?  Did you look to Faye when coding juggernaut?  What about the Bayeux spec?

I'll admit that I'm typing up this "issue" before properly digging into your code base, but I am hoping to get your thoughts even if I'm able to answer some of my own questions with a look through your code.

http://faye.jcoglan.com/
http://github.com/jcoglan/faye/
http://svn.cometd.com/trunk/bayeux/bayeux.html

**Comment by maccman** [comment]
Michael,
Yes, the Bayeux protocol was written before WebSockets, and is fairly complicated (due to complexities with comet). I haven't really looked at at Faye, but from the example docs it looks good. Also got a fairly simple interface to Juggernaut. I guess the difference is Faye probably has some more advanced features, such as authentication, and Juggernaut is much more simple. I wrote Juggernaut in a weekend, so there's not much code - should be pretty obvious how everything works. I guess, in terms of hackibility, Juggernaut should shine. Let me know how you find it.

Alex
