### ISSUE TITLE
"this.socket is undefined" error still happening in Firefox (3.6.12)

### ISSUE THREAD

**Issue by somebee** [maccman/juggernaut#38]
I've updated to latest trunk, confirmed that the changes here are included, (https://github.com/maccman/juggernaut/commit/2bccac6697d2f293d19b71ceb8fa97ea0492dfb1), but I'm still getting the "this.socket is undefined" error in Firefox.

**Comment by PanosJee** [comment]
I confirm this one

**Comment by wtm** [comment]
I'm seeing it in IE7 as well.

**Comment by michaelhood** [comment]
I'm seeing this, also.

Are those of you experiencing this running juggernaut in secure (https) mode? I am, and I'm seeing some other issues, too. Just trying to narrow down.

**Comment by PanosJee** [comment]
No clear. There is a new example index.html give it a look it seems application.js is deprecated.

**Comment by michaelhood** [comment]
thanks for the quick reply. yeah, I switched over.. still happening on occasion along with some other issues I'm noticing. I'm kind of at a loss on how to proceed.

There's at least 4 versions of WebSocketMain.swf floating around, too, between varying socket.io / socket.io-node / juggernaut commits, and it seems that at some point the AS<->JS interface within the SWF changed. So if you're experiencing this make sure you're careful not to mix these up. (most people are probably using the files as bundled, but since node-static doesn't work properly with https some of us are forced into hosting the files otherwise)

**Comment by wtm** [comment]
I am experiencing this in secure mode too.

PanosJee: what new example of index.html are you referring to?

**Comment by PanosJee** [comment]
https://github.com/maccman/juggernaut/blob/master/public/index.html

**Comment by gorman** [comment]
Has anyone had any luck figuring this out?

**Comment by PanosJee** [comment]
Use latest juggernaut and do not include application.js as in the past. You should include seperately socket.io and juggernaut.js
I do:
        <script src="http://cdn.socket.io/stable/socket.io.js"></script>
    <script src="http://<%=  request.host %>:8080/juggernaut.js" type="text/javascript" charset="utf-8"></script>

**Comment by maccman** [comment]
This is fixed in the latest version.
